### ISSUE TITLE
Unified creation method

### ISSUE THREAD

**Issue by plexus** [plexus/rubydataspec#1]
Making collection types interchangeable starts with having a unified way of instantiating them. For example Hamster currently has `Hamster.vector(1,2,3)` vs persistent_data_structures `Persistent::Vector.vector([1,2,3])`.

At a minimum I would suggest to standardize a class level `[]` method that takes a number of collection members. This is in line with the Ruby stdlib

``` ruby
Array[1,2,3]
Hash[:foo => :bar]
Set[3,3,4]
Matrix[[1,2,3],[4,5,6]]
```

This way libraries can do something like

``` ruby
module MyCoolLib
  Vector =  if RUBY_ENGINE == 'jruby'
    SomeJavaNative::Vector
  else
    SomeOtherImplementation::Vector
  end
end
```

or even make this completely configurable from the outside.

**Comment by headius** [comment]
If the method is going to live on the class it creates, I don't see the benefit of using `[]` over `new`, honestly (unless the benefit is that it's two characters shorter than .new?). I don't dislike `[]`, but I think having `[]` and not `new` is strange.

If it lives on a specific namespace, as in Hamster, obviously that's not an option. I don't know if I have a strong preference between Vector.new and SomeNamespace.vector.

**Comment by krainboltgreene** [comment]
Agreed, I'm a big proponent of using explicit words.

On Tue, May 27, 2014 at 12:35 PM, Charles Oliver Nutter <
notifications@github.com> wrote:

> If the method is going to live on the class it creates, I don't see the
> benefit of using [] over new, honestly (unless the benefit is that it's
> two characters shorter than .new?). I don't dislike [], but I think
> having [] and not new is strange.
> 
> If it lives on a specific namespace, as in Hamster, obviously that's not
> an option. I don't know if I have a strong preference between Vector.new
> and SomeNamespace.vector.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/plexus/rubydataspec/issues/1#issuecomment-44308301
> .

## 

Kurtis Rainbolt-Greene, Hacker
Software Developer
1631 8th St.
New Orleans, LA
70115

**Comment by plexus** [comment]
The reasoning here is that `[]` is consistent with how Ruby's built-in types work, whereas none of them implement a `.new` that takes items

``` ruby
irb(main):011:0> Array.new(4,5)
=> [5, 5, 5, 5]
irb(main):012:0> Hash.new(:foo => :bar)
=> {}
irb(main):014:0> Set.new(4,5,6)
ArgumentError: wrong number of arguments (3 for 0..1)
        from /home/arne/.rubies/ruby-2.0.0-p451/lib/ruby/2.0.0/set.rb:73:in `initialize'
        from (irb):14:in `new'
        from (irb):14
        from /home/arne/.rubies/ruby-2.0.0-p451/bin/irb:12:in `<main>'
irb(main):016:0> Matrix.new([1,2,3],[4,5,6])
NoMethodError: private method `new' called for Matrix:Class
        from (irb):16
        from /home/arne/.rubies/ruby-2.0.0-p451/bin/irb:12:in `<main>'
```

vs

``` ruby
irb(main):017:0> Array[4,5,6]
=> [4, 5, 6]
irb(main):018:0> Hash[:foo => :bar]
=> {:foo=>:bar}
irb(main):019:0> Set[4,5,6]
=> #<Set: {4, 5, 6}>
irb(main):020:0> Matrix[[1,2,3],[4,5,6]]
=> Matrix[[1, 2, 3], [4, 5, 6]]
```

**Comment by plexus** [comment]
The other reason I like `[]` is that it makes a nice concise `inspect` syntax as well, like what Matrix does above and what I've already done for Clojr/Persitent.
