### ISSUE TITLE
Add element to list or vector

### ISSUE THREAD

**Issue by plexus** [plexus/rubydataspec#3]
There are three types of possible semantics for this
- add element to the front
- add element to the back
- add element in the most natural/efficient way, e.g. to the front for a linked list

From quick inspection

Hamster::List
- `add`, `<<`: add to back
- `>>`: add to front
- `cons`: "natural" (add to front)

Hamster::Vector
- `add`, `<<`: add to back
- `cons`: "natural" (add to back)

Persistent::Vector
- `add`: add to back

Opinions? It would seem the minimum interface would be `<<` and `cons`, and optionally `>>` if prepending is supported.

Another option is to have `add` mean "add in natural/efficient" way instead of `cons` which might be less surprising for people that don't have a LISP history ;)

How about aliases like `add`, `append` or `prepend`? Start with standardizing a single strict interface, or already specify implementations should have certain aliases?

**Comment by krainboltgreene** [comment]
I'm super hard against methods that aren't words, so I have to vote heavy
for either primary add, append, prepend, or beg for aliases.

On Mon, May 19, 2014 at 9:22 PM, Arne Brasseur notifications@github.comwrote:

> There are three types of possible semantics for this
> - add element to the front
> - add element to the back
> - add element in the most natural/efficient way, e.g. to the front for
>   a linked list
> 
> From quick inspection
> 
> Hamster::List
> - add, <<: add to back
> - >>: add to front
> - cons: "natural" (add to front)
> 
> Hamster::Vector
> - add, <<: add to back
> - cons: "natural" (add to back)
> 
> Persistent::Vector
> - add: add to back
> 
> Opinions? It would seem the minimum interface would be << and cons, and
> optionally >> if prepending is supported.
> 
> Another option is to have add mean "add in natural/efficient" way instead
> of cons which might be less surprising for people that don't have a LISP
> history ;)
> 
> How about aliases like add, append or prepend? Start with standardizing a
> single strict interface, or already specify implementations should have
> certain aliases?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/plexus/rubydataspec/issues/3
> .

## 

Kurtis Rainbolt-Greene, Hacker
Software Developer
1631 8th St.
New Orleans, LA
70115

**Comment by plexus** [comment]
I'm fine with `append` and `prepend` for explicit add to front/back. The ast gem also has append, jQuery nodes have append/prepend, so it's not without precedent. 

Here's what I'm thinking
- Have `add`, aliased to `<<` for "natural" addition, i.e. front for cons-based list, back for vector
- Have `append` and `prepend` on all collections that support explicit insertion at back or front. (possibly only one of the two)
- Have `cons` be an alias for `add`/`<<` only on cons based list
- Usage of `>>` is rare in Ruby, I wouldn't push for it.

This conflicts with current usage in Hamster though
- `Hamster::List#<<` is an append, not a cons
- `Hamster::Vector#cons` is a prepend, in the above scheme it should not define cons

@krainboltgreene @headius @Who828 say I prepare a PR for Hamster/persistent_data_structure/clojr that implements the above, what would your reaction be?

Note that I'm striving for a minimal specified interface. Gem author can add whatever aliases they want, but programmers should be made aware that sticking to these methods will yield portable code.

**Comment by plexus** [comment]
Looping in @txus and @rylev to get some more opinions/data points.

**Comment by plexus** [comment]
And since @solnic and @mbj have a strong functional style maybe they have an opinion as well. :smile_cat:

**Comment by solnic** [comment]
I never define `<<`. I always make it an alias.

**Comment by headius** [comment]
@plexus A PR to make Hamster consistent with these names seems reasonable to me. Whether these are the right names or not...I'm not jumping into that bikeshed :-)

**Comment by krainboltgreene** [comment]
I would approve it.

On Tue, May 27, 2014 at 12:08 PM, Charles Oliver Nutter <
notifications@github.com> wrote:

> @plexus https://github.com/plexus A PR to make Hamster consistent with
> these names seems reasonable to me. Whether these are the right names or
> not...I'm not jumping into that bikeshed :-)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/plexus/rubydataspec/issues/3#issuecomment-44304983
> .

## 

Kurtis Rainbolt-Greene, Hacker
Software Developer
1631 8th St.
New Orleans, LA
70115

**Comment by rylev** [comment]
This looks good to me. Not sure about `add` with its alias `<<` though. These feel especially strange to me for linked lists. 

It's a shame you can't use `:` or `::` as a method name.

**Comment by plexus** [comment]
On second thought I agree `<<` is not a good name, mostly because in pretty much all existing usage it's a destructive operation. I didn't mention it in the README, the tests or the benchmarks so far, I wouldn't include it in the "spec".

I agree this is bordering on bikeshedding but if we're gonna standardize these methods for several projects for a long time to come I want to make sure they make sense. Anyway see the README for status so far. Next stretch of time I'll add these to Hamster and we can move on to the next bit.
